modLoader="javafml"
loaderVersion="[39,)"
license="GPL3"

[[mods]]
modId="cgm"
version="1.1.3"
displayName="MrCrayfish's Gun Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cgm/update.json"
displayURL="https://mrcrayfish.com/"
logoFile="cgm_banner.png"
authors="MrCrayfish"
description="MrCrayfish's Gun Mod adds in simple and straight forward weapons into Minecraft. They can be configured with many different attachments to add extra stats to your weapon and coloured to your personal liking. This mod adds ten weapons into the game!"

[[dependencies.cgm]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="controllable"
    mandatory=false
    versionRange="[0.14.1,)"
    ordering="AFTER"
    side="CLIENT"

[modproperties.cgm]
    catalogueImageIcon="cgm_icon.png"
    configuredBackground="minecraft:textures/block/stone_bricks.png"
